# General Jekyll Config
highlighter: pygments
url: example.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
img_url: https://github.com/xw393/xw393.github.io/tree/master/assets/images
